/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author ortega
 */
import Table.Table;
public class tabletrackGUI extends javax.swing.JFrame {

    /**
     * Creates new form tabletrackGUI
     */
    public tabletrackGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        checkTable1 = new javax.swing.JCheckBox();
        checkTable2 = new javax.swing.JCheckBox();
        checkTable3 = new javax.swing.JCheckBox();
        checkTable4 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        checkTable5 = new javax.swing.JCheckBox();
        checkTable6 = new javax.swing.JCheckBox();
        checkTable7 = new javax.swing.JCheckBox();
        checkTable8 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Table 1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Table 2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Table 3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Table 4");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/table.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/table.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/table.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/table.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        checkTable1.setText("Available?");
        checkTable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTable1ActionPerformed(evt);
            }
        });
        checkTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                checkTable1PropertyChange(evt);
            }
        });

        checkTable2.setSelected(true);
        checkTable2.setText("Available?");
        checkTable2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTable2ActionPerformed(evt);
            }
        });

        checkTable3.setText("Available?");
        checkTable3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTable3ActionPerformed(evt);
            }
        });

        checkTable4.setText("Available?");
        checkTable4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTable4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Table 5");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/table.png"))); // NOI18N
        jLabel10.setText("jLabel10");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Table 6");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/table.png"))); // NOI18N
        jLabel12.setText("jLabel12");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Table 7");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/table.png"))); // NOI18N
        jLabel14.setText("jLabel14");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Table 8");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/table.png"))); // NOI18N
        jLabel16.setText("jLabel16");

        checkTable5.setText("Available?");
        checkTable5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTable5ActionPerformed(evt);
            }
        });

        checkTable6.setSelected(true);
        checkTable6.setText("Available?");
        checkTable6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTable6ActionPerformed(evt);
            }
        });

        checkTable7.setText("Available?");
        checkTable7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTable7ActionPerformed(evt);
            }
        });

        checkTable8.setSelected(true);
        checkTable8.setText("Available?");
        checkTable8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTable8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(checkTable1)))
                    .addComponent(jLabel9)
                    .addComponent(checkTable5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(checkTable2)))
                    .addComponent(jLabel11)
                    .addComponent(checkTable6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(checkTable3)))
                    .addComponent(jLabel13)
                    .addComponent(checkTable7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkTable8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel15)
                        .addComponent(checkTable4)
                        .addComponent(jLabel4)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkTable1)
                    .addComponent(checkTable2)
                    .addComponent(checkTable3)
                    .addComponent(checkTable4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkTable5)
                    .addComponent(checkTable6)
                    .addComponent(checkTable7)
                    .addComponent(checkTable8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    Table[] table = new Table[8];
    
    private void checkTable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTable1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_checkTable1ActionPerformed

    private void checkTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_checkTable1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_checkTable1PropertyChange

    private void checkTable2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTable2ActionPerformed
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_checkTable2ActionPerformed

    private void checkTable3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTable3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_checkTable3ActionPerformed

    private void checkTable4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTable4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_checkTable4ActionPerformed

    private void checkTable5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTable5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_checkTable5ActionPerformed

    private void checkTable6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTable6ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_checkTable6ActionPerformed

    private void checkTable7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTable7ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_checkTable7ActionPerformed

    private void checkTable8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTable8ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_checkTable8ActionPerformed
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        boolean[] tabledata = tablesstate();
        
        for (int i =0; i<8; i++){
            table[i] = new Table(8,tabledata[i]);
            
       }
        
    }//GEN-LAST:event_formWindowClosing

     public boolean[] tablesstate(){
         boolean tables[] = new boolean[8];
         tables[0] = checkTable1.isSelected();
         tables[1] = checkTable2.isSelected();
         tables[2] = checkTable3.isSelected();
         tables[3] = checkTable4.isSelected();
         tables[4] = checkTable5.isSelected();
         tables[5] = checkTable6.isSelected();
         tables[6] = checkTable7.isSelected();
         tables[7] = checkTable8.isSelected();
         
         return tables;
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabletrackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabletrackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabletrackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabletrackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tabletrackGUI().setVisible(true);
            }
        });
        
        
        
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkTable1;
    private javax.swing.JCheckBox checkTable2;
    private javax.swing.JCheckBox checkTable3;
    private javax.swing.JCheckBox checkTable4;
    private javax.swing.JCheckBox checkTable5;
    private javax.swing.JCheckBox checkTable6;
    private javax.swing.JCheckBox checkTable7;
    private javax.swing.JCheckBox checkTable8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
